name: CI

on:
  pull_request:
    branches:
      - main  # ou o nome do branch de destino do PR

jobs:
  test:
    runs-on: ubuntu-latest  # Ou outro sistema operacional, conforme necessário

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build

    - name: Run tests
      run: dotnet test
